lessons = {
    "Beginner Signs": {
        "father": "https://www.youtube.com/watch?v=qnEnXpPwf3Q",
         "brother": "https://www.youtube.com/watch?v=ubl_XBstJ4U",
        "can": "https://www.youtube.com/watch?v=LFwUHtiaieI",
        "come": "https://example.com/videos/return.mp4",
        "daughter": "https://www.youtube.com/watch?v=CcxlT702U64",
        "drink": "https://www.youtube.com/watch?v=XI_SQyY7RTM",
        "eat": "https://www.youtube.com/watch?v=G4hrRXigjlc",
        "friend": "https://www.youtube.com/watch?v=Ayj0jSe5gMA",
        "go": "https://www.youtube.com/watch?v=tBj6aNif6aU",
        "good": "https://www.youtube.com/watch?v=g95ziUuJop4",
        "hello": "https://www.youtube.com/watch?v=8P_D36Q31HY",
        "mother": "https://www.youtube.com/watch?v=2fLWKVlHAwo",
        "name": "https://example.com/videos/return.mp4",
        "no": "https://www.youtube.com/watch?v=hREgM3no6V4",
        "yes": "https://www.youtube.com/watch?v=4XERt1YDVlU",
        "please": "https://www.youtube.com/watch?v=7yHxlPGtZxM",
        "help": "https://www.youtube.com/watch?v=8dewCwaoODw",
        "sit": "https://www.youtube.com/watch?v=oHYxE5S8Ydk",
        "sleep": "https://www.youtube.com/watch?v=SXCk6Y_tV2Y",
        "son": "https://www.youtube.com/watch?v=79_pbVR4XM8",
        "thank you": "https://www.youtube.com/watch?v=rX8DZUpiEtE",
    },
    "Intermediate Signs": {
        "cannot": "https://www.youtube.com/watch?v=hREgM3no6V4",
        "good morning": "https://www.youtube.com/watch?v=9MNUJpwR5JM",
        "good evening": "https://www.youtube.com/watch?v=OrE1JvCAcnA",
        "good afternoon": "https://www.youtube.com/watch?v=fbP7CZHlRmk",
        "good night": "https://www.youtube.com/watch?v=mvgLcTqUW_U",
        "you": "https://www.youtube.com/watch?v=zYurmt3b0NA",
        "how many": "https://www.youtube.com/watch?v=o6OCf2Sc38Y",
        "husband": "https://www.youtube.com/watch?v=cH5G5vgLVKg",
        "fine": "https://www.youtube.com/watch?v=P93As33pnlA",
        "i dont understand": "https://www.youtube.com/watch?v=9qem0R6kqvg",
        "like": "https://www.youtube.com/watch?v=JS5Z5GMI5PM",
        "stand": "https://www.youtube.com/watch?v=BMxaD5CPnF8",
        "want": "https://www.youtube.com/watch?v=gMzp0Lxn-K0",
        "what": "https://www.youtube.com/watch?v=KhtEk_u_uNg",
        "when": "https://www.youtube.com/watch?v=FdiiE-CV2cY",
        "where": "https://www.youtube.com/watch?v=EKkqMbl_8eg",
        "read": "https://www.youtube.com/watch?v=mcSQCFlwD3Y",
        "write": "https://www.youtube.com/watch?v=8UeIyPWzHbc",
        "return": "https://www.youtube.com/watch?v=g9EA3GcPQno",
    },
    "Sentence Formation": {
        "Hello! How are you?": "https://example.com/videos/how_are_you.mp4",
        "Please help me eat!": "https://example.com/videos/i_am_fine.mp4",
        "I am thirsty, can you help me?": "https://example.com/videos/what_is_your_name.mp4",
        "My name is __, nice to meet you!": "https://example.com/videos/what_is_your_name.mp4",
        "Stop, I dont understand.": "https://example.com/videos/what_is_your_name.mp4",
        "I am sorry, I dont know.": "https://example.com/videos/what_is_your_name.mp4",
        "Thank you, I am fine.": "https://example.com/videos/what_is_your_name.mp4",
        "Wait for me, I will return from home.": "https://example.com/videos/what_is_your_name.mp4",
        "Good morning, I know you.": "https://example.com/videos/what_is_your_name.mp4",
        "Can you help me stand?": "https://example.com/videos/what_is_your_name.mp4",
        
    },
    "Quizzes": {
        "Beginner Quiz": "https://example.com/quizzes/beginner",
        "Intermediate Quiz": "https://example.com/quizzes/intermediate",
        "Sentence Quiz": "https://example.com/quizzes/sentence",
    }
}
